// ════════════════════════════════════════════════════════════════
//  ANIMATION CONFIG
// ════════════════════════════════════════════════════════════════
export const ANIM = {
  walking:        { frames: 8,  fps: 12, loop: true,  spriteRow:  0 },
  sitting_down:   { frames: 6,  fps: 10, loop: false, spriteRow:  1 },
  standing_up:    { frames: 6,  fps: 10, loop: false, spriteRow: 11 },
  typing_normal:  { frames: 4,  fps:  6, loop: true,  spriteRow:  2 },
  typing_furious: { frames: 4,  fps: 16, loop: true,  spriteRow:  3 },
  thinking:       { frames: 6,  fps:  5, loop: true,  spriteRow:  4 },
  drinking_desk:  { frames: 8,  fps:  6, loop: false, spriteRow:  5 },
  spinning_chair: { frames:12,  fps: 10, loop: false, spriteRow:  6 },
  celebrating:    { frames:10,  fps: 14, loop: false, spriteRow:  7 },
  sitting_couch:  { frames: 4,  fps:  8, loop: false, spriteRow:  8 },
  sleeping:       { frames: 6,  fps:  4, loop: true,  spriteRow:  9 },
  drinking_beer:  { frames: 8,  fps:  6, loop: true,  spriteRow: 10 },
  phone:          { frames:10,  fps:  8, loop: true,  spriteRow: 12 },
  stretching:     { frames: 8,  fps:  5, loop: true,  spriteRow: 13 },
  at_coffee:      { frames: 8,  fps: 6,  loop: true,  spriteRow: 14 },
  at_fridge:      { frames: 6,  fps: 5,  loop: true,  spriteRow: 15 },
  eating:         { frames: 8,  fps: 5,  loop: true,  spriteRow: 16 },
  window_gaze:    { frames: 4,  fps: 3,  loop: true,  spriteRow: 17 },
  headphones:     { frames: 8,  fps: 8,  loop: true,  spriteRow: 18 },
  air_guitar:     { frames: 8,  fps: 10, loop: true,  spriteRow: 19 },
  yoga:           { frames: 6,  fps: 4,  loop: true,  spriteRow: 20 },
  reading:        { frames: 4,  fps: 3,  loop: true,  spriteRow: 21 },
  desk_nap:       { frames: 4,  fps: 3,  loop: true,  spriteRow: 22 },
  desk_yawn:      { frames: 12, fps: 4,  loop: false, spriteRow: 35 },
  doodling:       { frames: 6,  fps: 5,  loop: true,  spriteRow: 23 },
  plant_care:     { frames: 6,  fps: 4,  loop: true,  spriteRow: 24 },
  chatting_l:     { frames: 8,  fps: 6,  loop: true,  spriteRow: 25 },
  chatting_r:     { frames: 8,  fps: 6,  loop: true,  spriteRow: 25 },
  arguing_l:      { frames: 8,  fps: 8,  loop: true,  spriteRow: 26 },
  arguing_r:      { frames: 8,  fps: 8,  loop: true,  spriteRow: 26 },
  gossiping_l:    { frames: 6,  fps: 6,  loop: true,  spriteRow: 27 },
  gossiping_r:    { frames: 6,  fps: 6,  loop: true,  spriteRow: 27 },
  gaming:         { frames: 8,  fps:  8, loop: true,  spriteRow: 29 },
  treadmill:      { frames: 8,  fps: 14, loop: true,  spriteRow: 30 },
  bench_press:    { frames: 8,  fps: 8,  loop: true,  spriteRow: 30 },
  boxing:         { frames: 8,  fps: 10, loop: true,  spriteRow: 30 },
  cycling:        { frames: 8,  fps: 10, loop: true,  spriteRow: 30 },
  lifting_weights:{ frames: 8,  fps: 8,  loop: true,  spriteRow: 30 },
  ping_pong_l:    { frames: 6,  fps: 10, loop: true,  spriteRow: 31 },
  ping_pong_r:    { frames: 6,  fps: 10, loop: true,  spriteRow: 31 },
  smoking_beer:   { frames:12,  fps:  6, loop: true,  spriteRow: 32 },
  petting_cat:    { frames: 8,  fps:  5, loop: true,  spriteRow: 33 },
  cleaning:       { frames: 6,  fps:  5, loop: true,  spriteRow: 34 },
};
